/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.titanrobotics2022.geo;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class VectorTest {
    @Test
    public void assertTrueTest() {
        assertTrue(true);
    }
}
